trigger:
- main

resources:
- repo: self

variables:
  dockerImageName: 'secondaryService'
  dockerImageTag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Checkout@1
      displayName: 'Checkout Code'
      
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/secondaryService/Dockerfile'
        tags: |
          $(dockerImageName):$(dockerImageTag)

    - script: |
        echo "Docker Image built successfully with tag $(dockerImageName):$(dockerImageTag)"
      displayName: 'Confirm Docker Image Build'
